### PR TITLE
bump version and add changes

### PR DESCRIPTION
**Pull request by bounlu**

### CODE REVIEW

**Comment by lpantano** [comment]
Thank you!, can you bump the version to 1.31.1 since we need to make changes to devel in bioconductor? and please, add you as contributor!

**Comment by lpantano** [comment]
will this PR have the changes here as well: https://github.com/lpantano/isomiRs/pull/22?

**Comment by bounlu** [comment]
I submitted PR with some changes, but did some more changes on my repo, not sure why you all see them.

**Comment by lpantano** [comment]
Working on this tomorrow to merge to main. Is all ready from your side? @bounlu?

**Comment by bounlu** [comment]
Yes please go ahead. Thank you.

**Pull request merged**
